spring:
  application:
    name: codeAi

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0          # 不再警告
      timeout: 2000ms
      # password: your_password
      client-type: lettuce  # 默认就是 lettuce
      pool:
        enabled: true
        max-active: 8
        max-idle: 8
        min-idle: 0

  session:
    store-type: redis
    timeout: 2592000s

  profiles:
    active: stg

  datasource:
    url: jdbc:mysql://localhost:3306/an_ai_code
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8102
  servlet:
    context-path: /api
# Swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.aizihe.codeaai.controller